config/routes.rb
MaggieApp::Application.routes.draw do
  
  resources :messages, only: [:new, :create]
  
  root 'static_pages#home'
  
  match '/about', to: 'static_pages#new_about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/projects', to: 'static_pages#projects', via: 'get'
  
  match '/email', to: 'messages#new', via: 'get'
  
  
  
  
end

#   end

app/models/message.rb
class Message < ActiveRecord::Base
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+\@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}
  validates :content, presence: true, length: {minimum: 10}
  validates :checkbox, absence: true # { message: "You failed the human test. Please re-read the form and try again!" } # make sure that if the honeypot is checked the form is invalid
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  
  def new
    @message = Message.new
  end
  
  def create
    @message = Message.new(message_params)
    
    if @message.save
      MyMailer.visitor_email(@message).deliver
      flash[:success] = "Your email has been sent, and I can't wait to read it!"
      redirect_to root_path
    else
      render 'new'
    end
  end
  
  private
  
  def message_params
    params.require(:message).permit(:name, :email, :content, :checkbox)
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  end
  
  def about
  end
  
  def projects
  end
  
  def contact
  end
  
  def blog
  end
  
end

app/controllers/system_error_controller.rb
class SystemErrorController < ApplicationController
  
  def lost
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  
  def random_thing
    ["likes comfortable chairs", 
      "loves the color blue", 
      "wants to get sushi right now", 
      "orders tea, Earl Grey, hot at bars", 
      "devours information like movie theater popcorn", 
      "sometimes goes running",
      "doesn't believe in magic",
      "is still looking for a way to do all her work sitting outside",
      "prefers cold weather",
      "knows most of the rules in rugby",
      "is terrible at chess",
      "likes long walks on the beach",
      "prefers sunrises to sunsets",
      "has seen the proof that all natural numbers sum to -1/12 and believes it",
      "didn't discover Reddit until she was 23",
      "can't play the piano",
      "< insert funny phrase here >",
      "is entirely fueled by cheese curls"
    ].sample
  end
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="page-wrap footer-inner">
		<li>
			<small>
				&copy; Maggie Moreno
			</small>
		</li>
		<li>
			<small>
				Updated June, 2014
			</small>
		</li>
		<li>
			<small>
				<%= link_to "Email Me", email_path %>
			</small>
		</li>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar">
	<div class="navbar-inner">
		<div class="page-wrap navbar-container">
			<div class="page-wrap main-logo"><%= link_to "Maggie Moreno", root_path, id: "logo" %></div>
			<div class="page-wrap nav-links">
				<li><%= link_to "About Me", about_path %></li>
				<li><%= link_to "Projects", projects_path %></li>
				<li><%= link_to "Contact", contact_path%></li>
        <li><%= link_to "Blog", "http://blog.missmaggiemo.com/" %></li>
			</div>
		</div>
	</div> 
</header>

app/views/layouts/_shim.html.erb
<!-- [if lt IE 9] 
  <script scr="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif] -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Maggie Moreno</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= favicon_link_tag 'favicon.ico' %>
  <%= render 'layouts/shim'%>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-48666606-1', 'missmaggiemo.com');
    ga('send', 'pageview');

  </script>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		
		<% flash.each do |key, value| %>
		<%= content_tag(:div, value, class: "alert alert-#{key}")%>
			<!-- <div class="alert alert-<%= key %>"><%= value %></div> -->
		<% end %>
		
		<%= yield %>
		
	</div>
	<%= render 'layouts/footer' %>
</body>
</html>

app/views/messages/_form_for_message.html.erb
<%= form_for @message do |f|%>

	<%= render 'shared/error_messages', object: f.object %>

	<%= f.label :name %>
	<%= f.text_field :name, placeholder: "e.g., John from Nice People, Inc"%>

	<%= f.label :email %>
	<%= f.email_field :email, placeholder: "e.g., john@nice-people.com"%>
	
	<%= f.label :content %>
	<%= f.text_area :content, placeholder: "Your message here." %>
	
	<%= f.label :checkbox, "If you're human, leave this box unchecked!", id: "message_checkbox" %>
	<%= f.check_box :checkbox%>

	<%= f.submit "Send!", class: "btn btn-large"%>
	<!-- message is passed as a local variable -->

<% end %>

app/views/messages/new.html.erb
<div class="email">
	<div class="top center blue">
		<h1>Email me.</h1>
		<p>I'd love to hear from you!</p>
	</div>
	
	<div class="row">
		<div class="span8">
			<%= render 'form_for_message'%>
		</div>
	</div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>

<div id="error_explanation">
	<div class="alert alert-error">
		<!-- this is different from the flash-success, even though it uses a similar content tag -->
		The form contains <%= pluralize(object.errors.count, "error") %>.
	</div>
	<ul>
		<% object.errors.full_messages.each do |msg|%>
		<li>* <%= msg %></li>
		<% end %>
	</ul>
</div>

<% end %>

app/views/static_pages/about.html.erb
<div class="top center blue">
	<h1>I've been fortunate enough to rack up some interesting experiences.</h1>
	<p>Some of them are listed below.</p>
</div>
<div class="resume">
	<li class="res-sect"><h3>Skills</h3>
		<ul class="skill">
			<li><strong>Web Development</strong>
				<ul class="sect more-skill">
					<li>Web Development Languages and Tools
						<ul class="sect minor-list">
							<li><em>I’m proficient:</em>  Ruby on Rails</li>
							<li><em>I’ve seen it before:</em>  SQL, JavaScript, JSON, HTML, CSS</li>
						</ul>
					</li>
				</ul>
			</li>
		
			<li><strong>UX Research Methods</strong>
				<ul class="sect more-skill">
					<li>Information Presentation
						<ul class="sect minor-list">
							<li>Blog writing, PowerPoint/Keynote presentations, infographic-type graph design</li>
						</ul>
					</li>
					<li>Data Analysis Techniques
						<ul class="sect minor-list">
							<li>Basic data analysis techniques along with ANOVA, regression techniques, cluster analysis, random forests, data visualization</li>
						</ul>
					</li>
					<li>Experimental Design
						<ul class="sect minor-list">
							<li>Light-weight UI testing, lean UX, survey design (both online and mobile, large and small scale), A/B testing, focus groups</li>
						</ul>
					</li>
					<li>Statistical Languages and Tools
						<ul class="sect minor-list">
							<li><em>I’m proficient:</em>  R (including ggplot2), Python (including pandas), Ruby, Matlab, Excel (including pivot tables)</li>
							<li><em>I’ve seen it before:</em>  Tableau</li>
						</ul>
					</li>
				</ul>
			</li>
		</ul>
	</li>
	
	<li class="res-sect"><h3>Education</h3>
		<ul class="educat">
			<li><strong>BA</strong> (Psychology) 2010, University of Chicago</li>
			<li><strong>MSc</strong> (Cognitive Science) 2012, Università degli studi di Trento</li>
		</ul>
	</li>
	
	<li class="res-sect"><h3>Employment</h3>
		<ul class="year">
			<li><h4>2013</h4>
				<ul class="sect">
					<p>User Experience Intern at Immersion Corporation.</p>
					<p></p>
					<p><em>Major contributions:</em>  Small and large-scale user experience study design, survey design, data analysis (with R and Python), data management, and scientific writing.</p>
				</ul>
			</li>
			<li><h4>2011-2012</h4>
				<ul class="sect">
					<p>Research Assistant at SISSA, under the supervision of Giosuè Baggio. </p>
					<p></p>
					<p><em>Major contributions:</em>  The research, planning, and data analysis of a signaling games behavioral study. Experiments were run with Presentation software. Data was analyzed with Excel, Matlab, and R using analysis of variance techniques.</p>
				</ul>
			</li>
			<li><h4>2012</h4>
				<ul class="sect">
					<p>Research Consultant at Huskadu. </p>
					<p></p>
					<p><em>Major contributions:</em>  Researching competing websites, writing user experience surveys, and analyzing survey data. </p>
				</ul>
			</li>
			<li><h4>2011</h4>
				<ul class="sect">
					<p>Research Assistant in the Functional Neuroimaging Lab, Centro interdipartimentale Mente/Cervello (CIMeC), Università degli Studi di Trento, under the supervision of Dr. Uri Hasson and Dr. Pascale Tremblay.</p>
					<p></p>
					<p><em>Major contributions:</em>  Recruiting participants, administering consent forms, running behavioral experiments with Praat and Presentation.</p>
				</ul>
			</li>
			<li><h4>2009 – 2010</h4>
				<ul class="sect">
					<p>Research Assistant in the Department of Psychology of the University of Chicago, under the supervision of Dr. Howard Nusbaum.</p>
					<p></p>
					<p><em>Major contributions:</em>  Creating audio stimuli with Audacity and Praat, designing and running behavioral experiments with EPrime.</p>
				</ul>
			</li>
			<li><h4>2009</h4>
				<ul class="sect">
					<p>Research Assistant in the Department of Neurology at the University of Chicago, under the supervision of Dr. Leo Towle.</p>
					<p></p>
					<p><em>Major contributions:</em>  Working with raw EEG data in NeuroScan. Data was passed through a bandwidth filter, and epileptic events were tagged.</p>
				</ul>
			</li>
		</ul>
	</li>
</div>

app/views/static_pages/contact.html.erb
<div class="contact"> 
	<div class="top center blue">
		<h1>Contact me.</h1>
	</div>

	<div class="contact-text">
		<p>You can get a hold of me through one of these lovely online mediums:</p>
		<div class="page-wrap social-links">
			<li><%= link_to image_tag("facebook.png", alt: "Facebook"), "http://facebook.com/maggie.moreno", target: "_blank" %></li>
			<li><%= link_to image_tag("linkedin.png", alt: "LinkedIn"), "http://www.linkedin.com/in/maggiemoreno/", target: "_blank" %></li>
			<li><%= link_to image_tag("github.png", alt: "GitHub"), "https://github.com/missmaggiemo", target: "_blank" %></li>
			<li><%= link_to image_tag("gplus.png", alt: "Google+"), "https://www.google.com/+MaggieMoreno2312", target: "_blank" %></li>
		</div>
	
		<p> Or you can email me at <%= link_to "maggie@missmaggiemo.com", email_path %>.</p>
	
	</div>
</div>

app/views/static_pages/home.html.erb
<div class="page-wrap home">
	<li>
		<div class="thumbnail">
			<%= link_to image_tag("thumbnail.png", alt: "Maggie Moreno"), '/about'%>
		</div>
	</li>
	<li>
		<div class="top center">
			<h1><strong>Hi, I'm Maggie.</strong></h1>
			<p>I'm a <strong>web developer</strong> who</p>
      <p><%= random_thing %>.</p>
		</div>
	</li>
</div>

app/views/static_pages/new_about.html.erb
<div class="top center blue">
	<h1>A little about me.</h1>
	<p></p>
</div>
<div class="about">
	<div class="page-wrap topic">
		<div class="page-wrap pic">
			<%= image_tag("maggie_full.png", alt: "Maggie")%>
		</div>
		<div class="page-wrap text">
			<p>
				<strong><em>So who is this "Maggie" person, anyway?</em></strong><br><br>
				I'm so glad you asked! My education and background is in cognitive science and user experience research. I wanted to have a more impactful role in consumer-facing products, so I started learning web development in December, 2013. <br><br>
				When I'm not typing furiously on my computer, I like to go hiking, camping, skiing, and all manner of outdoorsy things. I'm more of a cat person than a dog person. I lived in Italy for a couple of years. I'm a Star Trek fan, a Kim Stanley Robinson fan, and yes, I loved the movie <%= link_to "Her (2013)", "http://www.imdb.com/title/tt1798709/", target: "_blank"%>.
			</p>
		</div>
	</div>
	<div class="page-wrap topic">
		<div class="page-wrap pic">
			<%= image_tag("education.png", alt: "Education")%>
		</div>
		<div class="page-wrap text">
			<p>
				<strong><em>I'm educated.</em></strong><br><br>
				I got my BA from the University of Chicago in 2010 and my MSc from l'Università degli studi di Trento in 2012. While I was at these prestigious institutions, I did a lot of research around the subject of language and communication. I wrote my master's thesis on <%= link_to "communication via signaling games", "https://docs.google.com/file/d/0B6EjfMEqe_MjM1ZUS3FoMFFLVlk/edit?usp=sharing", target: "_blank"%>.<br><br>
				I love learning, and I constantly take courses on <%= link_to "Coursera", "https://www.coursera.org/user/i/62da43c330791faf1444ba89f764e988", target: "_blank"%> and <%= link_to "Udacity", "https://www.udacity.com/", target: "_blank"%>.
			</p>
		</div>
	</div>

	<div class="page-wrap topic">
		<div class="page-wrap pic">
			<%= image_tag("research.png", alt: "Skills")%>
		</div>
		<div class="page-wrap text">
			<p>
				<strong><em>I'm skilled.</em></strong><br><br>
        I'm primarily a <%= link_to "Ruby on Rails", "http://rubyonrails.org/", target: "_blank" %> web developer, but I've also dabbled in <%= link_to "Google App Engine", "https://developers.google.com/appengine/?csw=1", target: "_blank" %> (with Python and webapp2). I'm rather new to the field, so expounding on any supposed expertise would be pure bluff. But I have come to web development brandishing my love of learning, so I hope to start putting technical feathers in my hat soon.<br><br>
				From my research background, I have a good knowledge base of statistical tools and scientific research methods. In the field of user experience research, work that I've done has included light-weight UI testing, lean UX, survey design (both online and mobile, large and small scale), A/B testing, and focus groups.
			</p>
		</div>
	</div>
	<div class="page-wrap topic">
		<div class="page-wrap pic">
			<%= image_tag("work_experience.png", alt: "Work")%>
		</div>
		<div class="page-wrap text">
			<p>
				<strong><em>I work hard.</em></strong><br><br>
				I'm currently a student at <%= link_to "App Academy", "http://www.appacademy.io/", target: "_blank"%>, but I am on the job hunt! So feel free to <%= link_to "email me", "/email", target: "_blank"%> if you know of any entry-level web developer positions opening up!<br><br>
				Recently, I spent about six months working as a user experience intern at <%= link_to "Immersion Corporation", "http://www.immersion.com/", target: "_blank"%>. Some of the work that I did there is listed on the <%= link_to "projects", "projects"%> page.
			</p>
		</div>
	</div>
	<div class="page-wrap topic">
		<div class="page-wrap pic">
			<%= image_tag("code.png", alt: "Code")%>
		</div>
		<div class="page-wrap text">
			<p>
				<strong><em>I code.</em></strong><br><br>
				Here's the full list, so far:<br><br>
				<%= link_to 'Ruby', 'https://www.ruby-lang.org/en/', target: '_blank'%> (including <%= link_to 'Rails', 'http://rubyonrails.org/', target: '_blank'%>), <%= link_to 'JavaScript', 'https://developer.mozilla.org/en-US/docs/Web/JavaScript', target: '_blank'%> (including <%= link_to 'jQuery', 'http://jquery.com/', target: '_blank'%> and <%= link_to 'Backbone.js', 'http://backbonejs.org/', target: '_blank'%>), <%= link_to 'JSON', 'http://www.json.org/', target: '_blank'%>, <%= link_to 'HTML', 'http://en.wikipedia.org/wiki/HTML', target: '_blank'%>, <%= link_to 'CSS', 'http://en.wikipedia.org/wiki/Cascading_Style_Sheets', target: '_blank'%> (and <%= link_to 'Sass', 'http://sass-lang.com/', target: '_blank'%>), SQL (and <%= link_to 'PostgreSQL', 'http://www.postgresql.org/', target: '_blank'%> ), Python (including <%= link_to 'Google App Engine', 'https://developers.google.com/appengine/?csw=1', target: '_blank'%>), <%= link_to 'R', 'http://www.r-project.org/', target: '_blank'%> (including <%= link_to 'ggplot2', 'http://ggplot2.org/', target: '_blank'%>)
			</p>
		</div>
	</div>
</div>

app/views/static_pages/projects.html.erb
<div class="top center blue">
	<h1>Here's what I've been up to lately.</h1>
	<p></p>
</div>

<div class="projects">
  
	<div class="page-wrap project">
		<div class="page-wrap pic">
			<%= link_to image_tag("a_A_logo_small.png", alt: "a/A"), "http://www.appacademy.io/", target: "_blank" %>
		</div>
		<div class="page-wrap text">
			<p>
        <strong><em>I'm a student at <%= link_to "App Academy", "http://www.appacademy.io/", target: "_blank" %>!</em></strong>
        <br><br>
				I post my notes and drawings from class on <%= link_to "Tumblr", "http://missmaggiemo.tumblr.com/", target: "_blank"%>, and I post projects to <%= link_to "Github", "https://github.com/missmaggiemo?tab=repositories", target: "_blank"%>.
      </p>
		</div>
	</div>

	<div class="page-wrap project">
		<div class="page-wrap pic">
			<%= link_to image_tag("findmy_logo.png", alt: "Findmy"), "http://www.findmy.in", target: "_blank" %>
		</div>
		<div class="page-wrap text">
			<p><strong><em><%= link_to "My final project for App Academy", "http://www.findmy.in", target: "_blank" %></em></strong>
        <br><br>
				This is a website that I built as my final project for App Academy. It utilizes the <%= link_to 'Yelp API V2', 'http://www.yelp.com/developers/documentation/v2/search_api', target: '_blank' %>, <%= link_to 'Google Maps V3', 'https://developers.google.com/maps/documentation/javascript/', target: '_blank' %>, and <%= link_to 'geolocation', 'http://www.w3schools.com/html/html5_geolocation.asp', target: '_blank' %>.
				<br><br>
				For more information, <%= link_to 'please visit the site', 'http://www.findmy.in', target: '_blank' %>! And feel free to check out the code on <%= link_to "Github", "https://github.com/missmaggiemo/find_my", target: "_blank"%>.
        </p>
		</div>
	</div>

	<div class="page-wrap project">
		<div class="page-wrap pic">
			<%= link_to image_tag("space_cruiser.png", alt: "Space Cruiser"), 'http://space-cruiser.missmaggiemo.com/', target: "_blank" %>
		</div>
		<div class="page-wrap text">
			<p>
        <strong><em><%= link_to 'An arcade-style sidescroller game in pure JavaScript.', 'http://space-cruiser.missmaggiemo.com/', target: '_blank' %></em></strong>
        <br><br>
        Space Cruiser is a sidescroller game that I made at App Academy, in the spirit of old arcade games.
        If you make it to the other side of the screen, you win! But if you hit an asteroid or if the other spaceship shoots you, you lose.<br><br>
        Check out the code on <%= link_to 'Github', 'https://github.com/missmaggiemo/space_cruiser', target: '_blank' %>!
      </p>
		</div>
	</div>
  
	<div class="page-wrap project">
		<div class="page-wrap pic">
			<%= link_to image_tag("trellino_logo.png", alt: "Trellino"), "http://trellino.missmaggiemo.com/", target: "_blank" %>
		</div>
		<div class="page-wrap text">
			<p>
        <strong><em><%= link_to "My first app with Backbone.js!", "http://trellino.missmaggiemo.com/", target: "_blank" %></em></strong>
        <br><br>
        Trellino is a light-weight spin on <%= link_to "Trello", "https://trello.com/", target: "_blank" %>. This app was built with Ruby on Rails and Backbone.js.
        For more information, check out the code on <%= link_to "Github", "https://github.com/missmaggiemo/trellino", target: "_blank" %>!
      </p>
		</div>
	</div>
  

	<div class="page-wrap project">
		<div class="page-wrap pic">
			<%= link_to image_tag("website_icon.png", alt: "This Website"), root_path, target: "_blank" %>
		</div>
		<div class="page-wrap text">
			<p>
        <strong><em>I made the website you're looking at right now!
        <%= link_to "(And its accompanying blog.)", "http://blog.missmaggiemo.com/", target: "_blank"%>
        </em></strong>
        <br><br>
				This site is an ongoing project for me.
        It's built with <%= link_to "Ruby on Rails", "http://rubyonrails.org/", target: "_blank"%>,
        and the source code is on <%= link_to "Github", "https://github.com/missmaggiemo/maggie_app", target: "_blank" %>.
        If you want to know more about it, <%= link_to "email me", email_path %>!
      </p>
		</div>
	</div>

	<div class="page-wrap project">
		<div class="page-wrap pic">
			<%= link_to image_tag("dev_survey.png", alt: "Developer Survey Results"), "http://blog.immersion.com/2013/11/evidence-for-the-awesomeness-of-haptics/", target: "_blank" %>
		</div>
		<div class="page-wrap text">
			<p><strong><em><%= link_to "Evidence for the Awesomeness of Haptics", "http://blog.immersion.com/2013/11/evidence-for-the-awesomeness-of-haptics/", target: "_blank" %></em></strong><br><br>
				<em>"We know that in the two years that the Immersion Haptic SDK has bee available, it has been downloaded over 3,000 times, and apps that utilize the Immersion Haptic SDK have been downloaded 24 million times. But what has been less clear to us is how developers feel about haptic feedback and the Immersion Haptic SDK. In August, Immersion launched a survey to collect feedback from developers on their experience with haptic feedback in apps and Immersion Haptic SDK.  The results were overwhelmingly positive and demonstrate the benefits and ease of use."</em><br><br>
				Blog post for <%= link_to "Immersion Corporation", "http://blog.immersion.com/", target: "_blank"%>.
			</p>
		</div>
	</div>



	<div class="page-wrap project">
		<div class="page-wrap pic">
			<%= link_to image_tag("mmf_article.png", alt: "White Paper"), "http://www.immersion.com/markets/automotive/portal/resources/white-papers.html", target: "_blank" %>
		</div>
		<div class="page-wrap text">
			<p><strong><em>The Value of Multimodal Feedback in Automotive User Interfaces.</em></strong><br><br>
				<em>"Multimodal feedback—audio and tactile feedback—can help mitigate the potential danger of touchscreens in cars by reducing glance times and improving reaction times to in-vehicle tasks. Moreover, users enjoy using interfaces with multimodal feedback more than visual feedback alone. This review includes a number of current studies exploring driver distraction, multimodal feedback in touchscreens, and multimodal feedback in vehicles. These studies show that multimodal feedback is an essential component for a safe, effective, and enjoyable in-vehicle touchscreen system."</em><br><br>
				White paper for Immersion Corporation.<br><br>
				<%= link_to "Download available at Immersion Corporation website.", "http://www.immersion.com/markets/automotive/portal/resources/white-papers.html", target: "_blank" %><br><br>
			</p>
		</div>
	</div>

</div>

app/views/system_error/lost.html.erb
<div class="top center blue">
	<h1>Oh no! A system error!</h1>
	<p>It seems like you're a little lost.</p>
</div>
<div class="page-wrap maintenance">
  <div class="page-wrap topic">
  	<div class="page-wrap pic">
  		<%= image_tag("rejected.gif", alt: "Maggie")%>
  	</div>
  	<div class="page-wrap text">
      <p>
        The page you were looking for either doesn't exist anymore, doesn't exist yet, or never existed in the first place.<br><br>
        Any of these options is pretty disappointing.<br><br>
        But if you're <em>sure</em> that you know what you were looking for, and you're <em>sure</em> that the URL is right, <%= link_to "please send me an email", email_path %>, and I'll do my best to fix it ASAP!
      </p>
    </div>
  </div>
</div>